blogger/config/routes.rb
Blogger::Application.routes.draw do
  resources :authors
  resources :author_sessions

  root :to => 'articles#index'
  resources :articles
  resources :comments
  resources :tags

  match 'login'   => 'author_sessions#new',     :as => :login
  match 'logout'  => 'author_sessions#destroy', :as => :logout

end

blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  def to_s
    name
  end

  has_many :taggings, :dependent => :destroy
  has_many :articles, :through => :taggings
end

blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, :only=> [:destroy]

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    tag_id = params[:id]
    
    if tag_id == 'all'
      tags = Tag.all
      tags.each do |tag|
        tag.destroy
      end

      flash[:message] = "All Tags Deleted!"
    else 
      tag = Tag.find(tag_id)
      tag.destroy
    
      flash[:message] = "Tag #{tag} Deleted!"
    end
   
    redirect_to tags_path 
  end
end

blogger/app/helpers/tags_helper.rb
module TagsHelper
end

blogger/app/views/tags/index.html.erb
<h1>Tags</h1>
<%= tag_list(@tags) %>
<br />
<%= link_to "Destroy All Tags", tag_path('all'), :method => :delete, :confirm => 'You sure you want to delete all tags?', :class => 'super-alert' %>

blogger/app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>